---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli

inputs:
- name: version
- name: artifact
- name: pipelines

run:
  path: pipelines/cf/tasks/integration-tests.sh
