---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli

inputs:
- name: app
- name: version
- name: pipelines
- name: artifact

run:
  path: pipelines/cf/tasks/integration-tests.sh
